packages:
  - test-webpack4
  - test-webpack5

catalogs:
  dev:
    '@antfu/eslint-config': ^4.12.0
    '@antfu/ni': ^24.3.0
    bumpp: ^10.1.0
    eslint: ^9.25.1
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.5.1
    simple-git-hooks: ^2.12.1
    webpack: ^5.89.0
    webpack-cli: ^5.1.4
  prod:
    glob: ^10.4.5
    minimatch: ^9.0.5
  test-webpack4:
    webpack: ^4.47.0
    webpack-cli: ^3.3.12
  test-webpack5:
    webpack: ^5.89.0
    webpack-cli: ^5.1.4
